agents:
  queue: "k8s-builders"

steps:
  - label: test tls cluster standup
    key: tls-up
    command: .buildkite/scripts/start_tls_cluster_testing.sh
    plugins:
      - docker#v5.4.0:
          image: glrp/atgt:1.0.2
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION

  - label: test tiered storage cluster standup
    key: storage-up
    command: .buildkite/scripts/start_tiered_storage_testing.sh
    plugins:
      - docker#v5.4.0:
          image: glrp/atgt:1.0.2
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
